name: CI/CD Pipeline Selenium

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer les dépendances (inclut chromedriver)
        run: npm install

      - name: Installer Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Installer un serveur HTTP statique (pour les tests locaux)
        run: npm install -g http-server

      - name: Démarrer le serveur HTTP
        run: http-server ./public -p 8080 &

      - name: Lancer les tests
        run: npm run test

      - name: Deployer avec Netlify
        if: success()
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
