name: CI/CD Pipeline Selenium

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer les dépendances
        run: npm install

      - name: Installer wait-on
        run: npm install -g wait-on

      - name: Setup Google Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Installer un serveur HTTP statique
        run: npm install -g http-server

      - name: Démarrer le serveur HTTP
        run: http-server ./public -p 8080 &

      - name: Attendre que le serveur soit prêt
        run: wait-on http://127.0.0.1:8080

      - name: Lancer les tests Selenium
        run: npm run test

      - name: Afficher les logs en cas d’échec
        if: failure()
        run: cat test-output.log || echo "Pas de log trouvé"

      - name: Déployer avec Netlify
        if: success()
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: ./public
