name: CI/CD Pipeline Selenium

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer les dépendances
        run: npm install

      # Utiliser l'action setup-chrome pour garantir une installation compatible
      - name: Setup Google Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable # Garder 'stable' pour les dernières versions

      - name: Installer un serveur HTTP statique (pour les tests locaux)
        run: npm install -g http-server

      - name: Démarrer le serveur HTTP
        run: http-server ./public -p 8080 &

      - name: Debug Chrome Path
        run: |
          which google-chrome
          ls -l /usr/bin/google-chrome
          ls -l /opt/google/chrome/chrome # Si le chemin est différent

      - name: Lancer les tests
        # Assurez-vous que http-server a bien démarré avant de lancer les tests
        run: npm run test

      - name: Deployer avec Netlify
        if: success()
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
