name: CI/CD Pipeline Selenium

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer les dépendances
        run: npm install

      - name: Installer Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Vérifier Chrome
        run: |
          which google-chrome
          google-chrome --version

      - name: Installer Xvfb
        run: sudo apt-get install -y xvfb

      - name: Lancer le serveur
        run: |
          npm install -g lite-server
          nohup lite-server > /dev/null 2>&1 &
          sleep 5

      - name: Lancer les tests
        run: npm run test

      - name: Déployer avec Netlify
        if: success()
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
